pipeline {
    agent any
    stages {
        stage('Setup Python') {
            steps {
                sh '''
                    venv_dir="venv"

                    create_venv() {
                        if [ ! -d "$venv_dir" ]; then
                            python3 -m venv "$venv_dir"
                            echo "venv created"
                        fi
                    }

                    deactivate_venv() {
                        if [ ! -z "$VIRTUAL_ENV" ]; then
                            deactivate
                            echo "venv deactivated"
                        fi
                    }

                    activate_venv() {
                        deactivate_venv

                        if [ -d "$venv_dir" ]; then
                            source "$venv_dir/bin/activate"
                            echo "venv activated"
                        else
                            echo "venv not found"
                            return 1
                        fi
                    }

                    install_dependencies() {
                        if [ -f "lab2/requirements.txt" ]; then
                            pip install -r lab2/requirements.txt -qq
                        else
                            echo "requirements not found"
                            return 1
                        fi
                    }

                    create_venv && activate_venv && install_dependencies
                '''
            }
        }
        stage('Create dataset') {
            steps {
                echo 'Start create dataset'
                sh 'python lab2/create_dataset.py'
                echo 'Finish create dataset'
            }
        }
        stage('Train model') {
            steps {
                echo 'Start train model'
                sh 'python lab2/train_model.py'
                echo 'Finish train model'
            }
        }
        stage('Make prediction') {
            steps {
                echo 'Start make prediction'
                sh 'python lab2/make_prediction.py'
                echo 'Finish make prediction'
            }
        }
    }
}
